name: lftp static
on:
  workflow_dispatch:
jobs:
  build:
    name: lftp build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: alpine:latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install build depenencies
        run: apk add autoconf automake bash bash-completion build-base curl git libtool linux-headers perl pkgconf
        shell: ash {0}

      - name: bootstrap
        run: bash build-script.sh

      - name: readline
        run: bash build-script.sh readline

      - name: ncurses
        run: bash build-script.sh ncurses

      - name: expat
        run: bash build-script.sh expat

      - name: libunistring
        run: bash build-script.sh libunistring

      - name: libiconv
        run: bash build-script.sh libiconv

      - name: gettext
        run: bash build-script.sh gettext

      - name: libidn
        run: bash build-script.sh libidn

      - name: zlib
        run: bash build-script.sh zlib

      - name: openssl
        run: bash build-script.sh openssl

      - name: lftp
        run: bash build-script.sh lftp

      - name: Create release name env
        run: echo 'lftp_release_name='$(strings /github/home/build/lftp-static/bin/lftp | grep '^lftp/' | head -n 1 | sed 's|/| |g') >> $GITHUB_ENV

      - name: Create tag env
        run: echo 'lftp_tag='$(strings /github/home/build/lftp-static/bin/lftp | grep '^lftp/' | head -n 1 | sed 's|lftp/||g') >> $GITHUB_ENV

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: /github/home/build/lftp-static/bin/lftp
          replacesArtifacts: true
          tag: "${{ env.lftp_tag }}"
          name: "${{ env.lftp_release_name }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
